/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

bool_t
xdr_Giudice(xdrs, objp)
	XDR *xdrs;
	Giudice *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->lettera, 30, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Item(xdrs, objp)
	XDR *xdrs;
	Item *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->candidato, 30, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_Giudice(xdrs, &objp->giudice))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->categoria))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->filename, 64, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->fase))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->voto))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Tabella(xdrs, objp)
	XDR *xdrs;
	Tabella *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->riga, TABELLA_SIZE, sizeof(Item), (xdrproc_t)xdr_Item))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Output(xdrs, objp)
	XDR *xdrs;
	Output *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->listaGiudici, MAX_GIUDICI, sizeof(Giudice), (xdrproc_t)xdr_Giudice))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Input(xdrs, objp)
	XDR *xdrs;
	Input *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->candidato, 30, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->operazione))
		return (FALSE);
	return (TRUE);
}
