/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFACTOR_H_RPCGEN
#define _XFACTOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define TABELLA_SIZE 5
#define MAX_GIUDICI 5

struct Giudice {
	char lettera[30];
};
typedef struct Giudice Giudice;
#ifdef __cplusplus
extern "C" bool_t xdr_Giudice(XDR *, Giudice*);
#elif __STDC__
extern  bool_t xdr_Giudice(XDR *, Giudice*);
#else /* Old Style C */
bool_t xdr_Giudice();
#endif /* Old Style C */


struct Item {
	char candidato[30];
	Giudice giudice;
	char categoria;
	char filename[64];
	char fase;
	int voto;
};
typedef struct Item Item;
#ifdef __cplusplus
extern "C" bool_t xdr_Item(XDR *, Item*);
#elif __STDC__
extern  bool_t xdr_Item(XDR *, Item*);
#else /* Old Style C */
bool_t xdr_Item();
#endif /* Old Style C */


struct Tabella {
	Item riga[TABELLA_SIZE];
};
typedef struct Tabella Tabella;
#ifdef __cplusplus
extern "C" bool_t xdr_Tabella(XDR *, Tabella*);
#elif __STDC__
extern  bool_t xdr_Tabella(XDR *, Tabella*);
#else /* Old Style C */
bool_t xdr_Tabella();
#endif /* Old Style C */


struct Output {
	Giudice listaGiudici[MAX_GIUDICI];
};
typedef struct Output Output;
#ifdef __cplusplus
extern "C" bool_t xdr_Output(XDR *, Output*);
#elif __STDC__
extern  bool_t xdr_Output(XDR *, Output*);
#else /* Old Style C */
bool_t xdr_Output();
#endif /* Old Style C */


struct Input {
	char candidato[30];
	char operazione;
};
typedef struct Input Input;
#ifdef __cplusplus
extern "C" bool_t xdr_Input(XDR *, Input*);
#elif __STDC__
extern  bool_t xdr_Input(XDR *, Input*);
#else /* Old Style C */
bool_t xdr_Input();
#endif /* Old Style C */


#define OPERAZIONIPROG ((rpc_uint)0x20000013)
#define OPERAZIONIVERS ((rpc_uint)1)

#ifdef __cplusplus
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern "C" Output * classifica_giudici_1(void *, CLIENT *);
extern "C" Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO ((rpc_uint)2)
extern "C" void * esprimi_voto_1(Input *, CLIENT *);
extern "C" void * esprimi_voto_1_svc(Input *, struct svc_req *);
#define GETTABELLA ((rpc_uint)3)
extern "C" Tabella * gettabella_1(void *, CLIENT *);
extern "C" Tabella * gettabella_1_svc(void *, struct svc_req *);

#elif __STDC__
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern  Output * classifica_giudici_1(void *, CLIENT *);
extern  Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO ((rpc_uint)2)
extern  void * esprimi_voto_1(Input *, CLIENT *);
extern  void * esprimi_voto_1_svc(Input *, struct svc_req *);
#define GETTABELLA ((rpc_uint)3)
extern  Tabella * gettabella_1(void *, CLIENT *);
extern  Tabella * gettabella_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern  Output * classifica_giudici_1();
extern  Output * classifica_giudici_1_svc();
#define ESPRIMI_VOTO ((rpc_uint)2)
extern  void * esprimi_voto_1();
extern  void * esprimi_voto_1_svc();
#define GETTABELLA ((rpc_uint)3)
extern  Tabella * gettabella_1();
extern  Tabella * gettabella_1_svc();
#endif /* Old Style C */

#endif /* !_XFACTOR_H_RPCGEN */
